/*
 * Domeneshop API Documentation
 *
 * # Overview  Domeneshop offers a simple, REST-based API, which currently supports the following features:  - List domains - List invoices - Create, read, update and delete DNS records for domains - Create, read, update and delete HTTP forwards (\"WWW forwarding\") for domains - Dynamic DNS (DDNS) update endpoints for use in consumer routers  More features are planned, including:  - Web hosting administration - Email address and email user/account administration  # Testing period  The API service is in version 0, which means it is possible that the interface will change rapidly during the testing period. For that reason, **the documentation on these pages may sometimes be outdated.**  Additionally, we make no guarantees about the stability of the API service during this testing period, and therefore ask customers to be careful with using the service for business critical purposes.  # Authentication  The Domeneshop API currently supports only one method of authentication, **HTTP Basic Auth**. More authentication methods may be added in the future.  To generate credentials, visit <a href=\"https://www.domeneshop.no/admin?view=api\" target=\"_blank\">this page</a> after logging in to the control panel on our website:  <a href=\"https://www.domeneshop.no/admin?view=api\" target=\"_blank\">https://www.domeneshop.no/admin?view=api</a>  # Libraries  Domeneshop maintains multiple API libraries to simplify using the API. Please note that these libraries have the same stability guarantees to the API while the API is in version 0.  The libraries may be found in our [Github repository](https://github.com/domeneshop/).  Domeneshop also maintains a plugin for [EFF's Certbot](https://certbot.eff.org/), which automates issuance and renewal of SSL-certificates on your own servers for domains that use Domeneshop's DNS service. This plugin is found in our Github repository [here](https://github.com/domeneshop/certbot-dns-domeneshop).  <SecurityDefinitions /> 
 *
 * API version: v0
 * Contact: kundeservice@domeneshop.no
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package domeneshop

import (
	"encoding/json"
)

// DSAllOf struct for DSAllOf
type DSAllOf struct {
	Type string `json:"type"`
	// The value of the record.
	Data string `json:"data"`
	// DS record tag.
	Tag int32 `json:"tag"`
	// DS record algorithm.
	Alg int32 `json:"alg"`
	// DS record digest type.
	Digest int32 `json:"digest"`
}

// NewDSAllOf instantiates a new DSAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDSAllOf(type_ string, data string, tag int32, alg int32, digest int32, ) *DSAllOf {
	this := DSAllOf{}
	this.Type = type_
	this.Data = data
	this.Tag = tag
	this.Alg = alg
	this.Digest = digest
	return &this
}

// NewDSAllOfWithDefaults instantiates a new DSAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDSAllOfWithDefaults() *DSAllOf {
	this := DSAllOf{}
	return &this
}

// GetType returns the Type field value
func (o *DSAllOf) GetType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DSAllOf) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DSAllOf) SetType(v string) {
	o.Type = v
}

// GetData returns the Data field value
func (o *DSAllOf) GetData() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DSAllOf) GetDataOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DSAllOf) SetData(v string) {
	o.Data = v
}

// GetTag returns the Tag field value
func (o *DSAllOf) GetTag() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *DSAllOf) GetTagOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *DSAllOf) SetTag(v int32) {
	o.Tag = v
}

// GetAlg returns the Alg field value
func (o *DSAllOf) GetAlg() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.Alg
}

// GetAlgOk returns a tuple with the Alg field value
// and a boolean to check if the value has been set.
func (o *DSAllOf) GetAlgOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Alg, true
}

// SetAlg sets field value
func (o *DSAllOf) SetAlg(v int32) {
	o.Alg = v
}

// GetDigest returns the Digest field value
func (o *DSAllOf) GetDigest() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.Digest
}

// GetDigestOk returns a tuple with the Digest field value
// and a boolean to check if the value has been set.
func (o *DSAllOf) GetDigestOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Digest, true
}

// SetDigest sets field value
func (o *DSAllOf) SetDigest(v int32) {
	o.Digest = v
}

func (o DSAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["tag"] = o.Tag
	}
	if true {
		toSerialize["alg"] = o.Alg
	}
	if true {
		toSerialize["digest"] = o.Digest
	}
	return json.Marshal(toSerialize)
}

type NullableDSAllOf struct {
	value *DSAllOf
	isSet bool
}

func (v NullableDSAllOf) Get() *DSAllOf {
	return v.value
}

func (v *NullableDSAllOf) Set(val *DSAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableDSAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableDSAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDSAllOf(val *DSAllOf) *NullableDSAllOf {
	return &NullableDSAllOf{value: val, isSet: true}
}

func (v NullableDSAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDSAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


